### ISSUE TITLE
Can't easily new tokens to a vanilla Journal Entry

### ISSUE THREAD

**Issue by spetzel2020** [spetzel2020/quick-encounters#115]
- Foundry v10
- Quick Encounters 1.1.0

1. Create and open a new Journal Entry Page
2. Select  tokens
3. Press the [Fist] icon (because there is no [Add] button to use), get the following error:

`Reference Error: aciveQuickEncounter is not defined`

**Comment by spetzel2020** [comment]
Full error from the console:
```
Uncaught Error: ReferenceError: activeQuickEncounter is not defined
    at Dialog3.submit (QuickEncounter.js:1841:19)
    at Dialog3._onClickButton (QuickEncounter.js:1832:14)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```

**Comment by spetzel2020** [comment]
Would be fixed by #26

**Comment by spetzel2020** [comment]
A couple of other alternative ideas:
- Add a button into the vanilla JE that is specific to QEs
- Press the QE button on the left-quick-bar to create a new JE (not to just pop up the tutorial)

But what is happening when you select tokens **without** opening an existing JE? We're creating a new one.

**Comment by spetzel2020** [comment]
Closing as can't reproduce; in 1.1.3 this behaves in several different ways:
1. If you have a vanilla Journal Entry with no page, then the Tutorial is opened
2. If you have a vanilla JE with a created page, then that page is ignored and a completely new JE is created. This is slightly weird but manageable
3. If you have a JE with an existing QE, you are given the Run, Add, Create New dialog. However if you select [Add], nothing happens. Opened as new Issue

**Comment by spetzel2020** [comment]
Reopened for the specific case where you have an existing JE without any QEs in it and want to add a QE (a common use case would be existing adventure text where you want to associate QEs with the text). Instead of creating a completely new JE, it should use a currently open one (probably after asking)

**Comment by spetzel2020** [comment]
Fixed Option 2 above in https://github.com/spetzel2020/quick-encounters/issues/115#issuecomment-1504639941) to identify the open JE and use that

In 1.1.4b (not released)
