### ISSUE TITLE
Fix deprecation warnings

### ISSUE THREAD

**Issue by spetzel2020** [spetzel2020/quick-encounters#134]
From Issue #133 
```
commons.js:1922 Error: You are accessing PlaceableObject#data which is no longer used and instead the Document class should be referenced directly as PlaceableObject#document.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at Object.logCompatibilityWarning (commons.js:1911:19)
    at Token5e.get (foundry.js:25615:23)
    at QuickEncounter.js:546:75
    at Array.filter (<anonymous>)
    at QuickEncounter.runAddOrCreate (QuickEncounter.js:546:61)
    at Object.onClick (QuickEncounter.js:502:50)
    at SceneControls._onClickTool (foundry.js:71647:52)
    at HTMLLIElement.dispatch (jquery.min.js:2:43336)
    at y.handle (jquery.min.js:2:41320)
logCompatibilityWarning @ commons.js:1922
get @ foundry.js:25615
(anonymous) @ QuickEncounter.js:546
runAddOrCreate @ QuickEncounter.js:546
onClick @ QuickEncounter.js:502
_onClickTool @ foundry.js:71647
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

2commons.js:1922 Error: You are accessing PlaceableObject#data which is no longer used and instead the Document class should be referenced directly as PlaceableObject#document.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at Object.logCompatibilityWarning (commons.js:1911:19)
    at Token5e.get (foundry.js:25615:23)
    at QuickEncounter.js:547:72
    at Array.filter (<anonymous>)
    at QuickEncounter.runAddOrCreate (QuickEncounter.js:547:58)
    at Object.onClick (QuickEncounter.js:502:50)
    at SceneControls._onClickTool (foundry.js:71647:52)
    at HTMLLIElement.dispatch (jquery.min.js:2:43336)
    at y.handle (jquery.min.js:2:41320)
logCompatibilityWarning @ commons.js:1922
get @ foundry.js:25615
(anonymous) @ QuickEncounter.js:547
runAddOrCreate @ QuickEncounter.js:547
onClick @ QuickEncounter.js:502
_onClickTool @ foundry.js:71647
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

**Comment by spetzel2020** [comment]
Occurring because all tests for `isFoundryV10` were not firing for Foundry V11; fixed by changing to `isFoundryV10Plus`
Fixed in 1.1.5b
