### ISSUE TITLE
Foundry v10: TokenDocument5e MOdel Validation errors because x,y not integer

### ISSUE THREAD

**Issue by spetzel2020** [spetzel2020/quick-encounters#135]
```
Uncaught (in promise) Error: TokenDocument5e Model Validation Errors
[TokenDocument5e.x]: must be an integer
[TokenDocument5e.y]: must be an integer
    at SchemaField._validateType (commons.js:4098:15)
    at SchemaField.validate (commons.js:3824:37)
    at TokenDocument5e.validate (commons.js:5492:35)
    at new DataModel (commons.js:5269:26)
    at new Document (commons.js:5811:3)
    at new BaseToken (commons.js:10169:3)
    at new ClientDocumentMixin (foundry.js:13053:5)
    at new <anonymous> (foundry.js:12293:5)
    at new TokenDocument (foundry.js:21840:5)
    at new TokenDocument5e (token.mjs:6:16)
_validateType	@	commons.js:4098
validate	@	commons.js:3824
validate	@	commons.js:5492
DataModel	@	commons.js:5269
Document	@	commons.js:5811
BaseToken	@	commons.js:10169
ClientDocumentMixin	@	foundry.js:13053
(anonymous)	@	foundry.js:12293
TokenDocument	@	foundry.js:21840
TokenDocument5e	@	token.mjs:6
getTokenDocument	@	foundry.js:16492
generateFullExtractedActorTokenData	@	QuickEncounter.js:1393
await in generateFullExtractedActorTokenData (async)		
(anonymous)	@	QESheet.js:126
dispatch	@	jquery.min.js:2
y.handle	@	jquery.min.js:2
```

This is probably occurring because at `QuickEncounter.js#1379` we compute random `(x,y)` coordinates and should (but don't currently) round them

**Comment by spetzel2020** [comment]
Probably erroring because of `undefined` errors when no Map Note existed, but fixed to `round()` anyway

**Comment by spetzel2020** [comment]
Released in 1.1.5
