### ISSUE TITLE
Foundry v12 Compatibility: Die roll generation of number of Actors is broken

### ISSUE THREAD

**Issue by spetzel2020** [spetzel2020/quick-encounters#143]
1. Open an existing QE
2. Run the QE

The default number (1) is used for the number of generated tokens. Neither a specified number (e.g. 6) or a die roll (e.g. 1d4-2) seems to work.

The following error is shown in the console:
```
Error: The async option for Roll#evaluate has been removed. Use Roll#evaluateSync for synchronous roll evaluation.
    at Object.logCompatibilityWarning (foundry-esm.js:4474:19)
    at Roll.evaluate (foundry-esm.js:46449:23)
    at QuickEncounter.getNumActors (QuickEncounter.js:1332:23)
    at QuickEncounter.generateFullExtractedActorTokenData (QuickEncounter.js:1395:46)
    at async QuickEncounter.run (QuickEncounter.js:1209:9)
```

**Comment by spetzel2020** [comment]
Fixed in 1.2.3c (not yet released)

Need to test with v10.
