### ISSUE TITLE
Fix v10 Deprecation warnings

### ISSUE THREAD

**Issue by spetzel2020** [spetzel2020/quick-encounters#145]
More:

- Fix v10 deprecation warnings
```
Error: You are accessing the NoteDocument#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1692:19)
    at NoteDocument._logV10CompatibilityWarning (commons.js:6617:14)
    at get data [as data] (commons.js:6517:24)
    at QuickEncounter.createFrom (QuickEncounter.js:649:50)
logCompatibilityWarning @ commons.js:1703

commons.js:1703 Error: You are accessing the Actor5e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1692:19)
    at Actor5e._logV10CompatibilityWarning (commons.js:6617:14)
    at get data [as data] (commons.js:6517:24)
    at QuickEncounter.computeTotalXP (QuickEncounter.js:1592:99)
    at QuickEncounter.renderTotalXPLine (QuickEncounter.js:1606:30)
    at QuickEncounter.displayQEDialog (QuickEncounter.js:1736:34)
    at Object.onRenderJournalPageSheet [as fn] (QuickEncounter.js:1719:28)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at JournalSheet._renderPageViews (foundry.js:64385:15)
logCompatibilityWarning @ commons.js:1703

commons.js:1703 Error: You are accessing the Actor5e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1692:19)
    at Actor5e._logV10CompatibilityWarning (commons.js:6617:14)
    at get data [as data] (commons.js:6517:24)
    at QuickEncounter.computeTotalXP (QuickEncounter.js:1592:99)
    at QuickEncounter.renderTotalXPLine (QuickEncounter.js:1606:30)
    at QESheet.computeCombatantsForDisplay (QESheet.js:207:40)
    at QESheet.getData (QESheet.js:148:20)
    at QESheet._render (foundry.js:5067:29)
    at QESheet._render (foundry.js:5780:17)
    at QESheet._render (QESheet.js:88:22)
logCompatibilityWarning @ commons.js:1703

commons.js:1703 Error: You are accessing PlaceableObject#data which is no longer used and instead the Document class should be referenced directly as PlaceableObject#document.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at Object.logCompatibilityWarning (commons.js:1692:19)
    at Tile.get (foundry.js:24731:23)
    at QuickEncounter.js:815:26
    at Array.map (<anonymous>)
    at QuickEncounter.addTiles (QuickEncounter.js:813:51)
    at QuickEncounter.add (QuickEncounter.js:706:18)
    at QuickEncounter.runAddOrCreate (QuickEncounter.js:547:39)
    at HTMLButtonElement.<anonymous> (QESheet.js:138:67)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
logCompatibilityWarning @ commons.js:1703

commons.js:1703 Error: You are accessing PlaceableObject#data which is no longer used and instead the Document class should be referenced directly as PlaceableObject#document.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at Object.logCompatibilityWarning (commons.js:1692:19)
    at Tile.get (foundry.js:24731:23)
    at QuickEncounter.js:817:26
    at Array.map (<anonymous>)
    at QuickEncounter.addTiles (QuickEncounter.js:813:51)
    at QuickEncounter.add (QuickEncounter.js:706:18)
    at QuickEncounter.runAddOrCreate (QuickEncounter.js:547:39)
    at HTMLButtonElement.<anonymous> (QESheet.js:138:67)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
logCompatibilityWarning @ commons.js:1703
```

_Originally posted by @spetzel2020 in https://github.com/spetzel2020/quick-encounters/issues/28#issuecomment-1286245736_

**Comment by spetzel2020** [comment]
Already fixed in QE 0.8 and 1.0
