### ISSUE TITLE
Foundry 10 Testing 1 (10.275) Compatibililty error

### ISSUE THREAD

**Issue by spetzel2020** [spetzel2020/quick-encounters#92]
```
Error: You are accessing the Actor5e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1218:19)
    at Actor5e._logV10CompatibilityWarning (commons.js:5998:14)
    at get data [as data] (commons.js:5898:24)
    at QuickEncounter.computeTotalXP (QuickEncounter.js:1465:39)
    at QuickEncounter.renderTotalXPLine (QuickEncounter.js:1479:30)
    at QESheet.computeCombatantsForDisplay (QESheet.js:188:48)
    at QESheet.getData (QESheet.js:131:20)
    at QESheet._render (foundry.js:4807:29)
    at QESheet._render (foundry.js:5530:17)
    at QESheet._render (QESheet.js:77:22)
```

**Comment by spetzel2020** [comment]
Fixed in 1.0.4i

**Comment by spetzel2020** [comment]
Released in 1.0.4
