### ISSUE TITLE
Foundry v10 Testing 3 (Build 277). Can't create new QE from captured tokens

### ISSUE THREAD

**Issue by spetzel2020** [spetzel2020/quick-encounters#97]
Select tokens on the Scene and then press the QE (fist) icon and get:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'controlled')
    at QuickEncounter.runAddOrCreate (QuickEncounter.js:462:60)
    at Object.onClick (QuickEncounter.js:424:50)
    at SceneControls._onClickTool (foundry.js:63732:52)
    at HTMLLIElement.dispatch (jquery.min.js:2:43064)
    at v.handle (jquery.min.js:2:41048)
```

**Comment by spetzel2020** [comment]
Fixed in 1.0.4l
